### ISSUE TITLE
[Bug]: Error when calling `messageLog`

### ISSUE THREAD

**Issue by Pagliacii** [chrisgrieser/nvim-chainsaw#1]
### Bug Description

When I call `require('chainsaw').messageLog()`, this traceback pops:

```
.../nvim-data/lazy/nvim-chainsaw/lua/chainsaw/init.lua:31: attempt to call field 'normal' (a nil value)
stack traceback:
  .../nvim-data/lazy/nvim-chainsaw/lua/chainsaw/init.lua:31: in function 'messageLog'
```

`utils.normal` is a local function, see below:

https://github.com/chrisgrieser/nvim-chainsaw/blob/1932aae94a3975fbf010ef179156977e994eb30a/lua/chainsaw/init.lua#L31

https://github.com/chrisgrieser/nvim-chainsaw/blob/1932aae94a3975fbf010ef179156977e994eb30a/lua/chainsaw/utils.lua#L4

### To Reproduce

1. Install this plugin
2. call `require("chainsaw").messageLog()`

### neovim version

```Text
NVIM v0.10.0-dev-1988+g1ef60ea65
```

### Make sure you have done the following

- [X] I have updated to the latest version of the plugin.

**Comment by chrisgrieser** [comment]
overlooked that one when refactoring. Thanks, is fixed
