### ISSUE TITLE
[Contact]: debugprint.nvim

### ISSUE THREAD

**Issue by andrewferrier** [chrisgrieser/nvim-chainsaw#10]
### Bug Description

Hey @chrisgrieser wasn't sure of another way to get hold of you outside a GitHub issue, apologies for doing it this way. Feel free to connect with me on email at myfirstname@myfirstnamemylastname.com (based on my GitHub handle) if you like.

Anyway, I'm the maintainer of https://github.com/andrewferrier/debugprint.nvim, just thought you might be interested in this since there's some similarity with what you're doing with `nvim-chainsaw`. I guess we came to some of the same ideas independently which is great, just thought you might like to know about it in case there's any ideas you want to adapt or combine efforts in some way. Totally up to you...

By the way, I use both your `gx.nvim` and `nvim-various-textobjs` in my own dotfiles, thanks so much for maintaining these!

### To Reproduce

x

### neovim version

```Text
x
```

### Make sure you have done the following

- [X] I have updated to the latest version of the plugin.

**Comment by andrewferrier** [comment]
Oh, and in the interests of full transparency, this is where I became aware of nvim-chainsaw: https://www.reddit.com/r/neovim/comments/1ca3rm8/comment/l17d44q/. I did add it to my README comparison table (any corrections gladly accepted!) and added AppleScript support (good idea) to `debugprint` (I know you're MIT licensed but still wanted to tell you in the interests of full disclosure!).

**Comment by chrisgrieser** [comment]
Hi! Yeah, I also wasn't aware of there already was a similar (lua) plugin. 

Yeah, I can see that our plugins follow a similar goal. And I think debugprint is definitely more feature rich. Nonetheless, I think I'll keep on using chainsaw, simply for the fact that the code base is much more compact (~400 lines vs. ~3000 lines according to `tokei`), making it easy to maintain.

I also don't mind the healthy "competition", though I prefer to see it as a healthy redundancy which makes ecosystems more stable overall. (Well, at least if it is not in oversaturated areas such as status line or session management plugins. 😅)

> I did add it to my README comparison table (any corrections gladly accepted!)

You might add the fact that chainsaw supports a bunch of log statement types (beepLog, timeLog, etc.). Or the LoC count :P

Anyway, also added a small section on similar plugins to the chainsaw-docs to point people to debugprint if they are looking for more functionality. 

> added AppleScript support (good idea) to debugprint (I know you're MIT licensed but still wanted to tell you in the interests of full disclosure!).

Haha, no worries! One or two lines of code does really is such a small amount that is really does not cross the threshold of requiring credit!

**Comment by andrewferrier** [comment]
> Hi! Yeah, I also wasn't aware of there already was a similar (lua) plugin.
> 
> Yeah, I can see that our plugins follow a similar goal. And I think debugprint is definitely more feature rich. Nonetheless, I think I'll keep on using chainsaw, simply for the fact that the code base is much more compact (~400 lines vs. ~3000 lines according to `tokei`), making it easy to maintain.

Of course, totally fine, wouldn't expect you to give up your project :)

> I also don't mind the healthy "competition", though I prefer to see it as a healthy redundancy which makes ecosystems more stable overall. (Well, at least if it is not in oversaturated areas such as status line or session management plugins. 😅)

Haha yes, I think that's a much better attitude  :) Hopefully an opportunity to bounce ideas off each other too.

> You might add the fact that chainsaw supports a bunch of log statement types (beepLog, timeLog, etc.). Or the LoC count :P

I think that's totally fair! My table was perhaps a little biased on reflection. I've added some of that, although I may adopt some of those ideas for debugprint, let's see ;) I had thought about adding support for 'sleeps' also.

> Anyway, also added a small section on similar plugins to the chainsaw-docs to point people to debugprint if they are looking for more functionality.

Cool, I appreciate that, that's fantastic. Obviously I'll keep the comparison table in my README too and will try to keep it fair and balanced :) Any feedback always welcome...

> > added AppleScript support (good idea) to debugprint (I know you're MIT licensed but still wanted to tell you in the interests of full disclosure!).
> 
> Haha, no worries! One or two lines of code does really is such a small amount that is really does not cross the threshold of requiring credit!

:)

Feel free to close this issue by the way. You can always reach me on GitHub or at the email I mentioned if you want to discuss something that's not specifically an issue.

**Comment by chrisgrieser** [comment]
sure, will do!
