### ISSUE TITLE
[Bug]: multi-line logs are not removed

### ISSUE THREAD

**Issue by dlvhdr** [chrisgrieser/nvim-chainsaw#13]
### Bug Description

I use `prettier` to format my code so when a log line is too long it will spread it across multiple lines.
Then when I try to remove the lines with `removeLogs` it only removes the first line of the log.
Example:
```ts
console.log("[🪲 dlvhdr] beep 🔵 will return", {
  data: [
    {
      id: `cluster-${services[0].k8sClusterName}`,
      name: services[0].k8sClusterName ?? "",
      kind: WorkspaceKind.Cluster,
      value: {
        clusterName: services[0].k8sClusterName ?? "",
      },
    },
  ],
});
```

### To Reproduce

1. Create a long log
2. Run some formatter or manually spread it to multiple lines
3. Observe `removeLogs` only removes the first line.

### neovim version

```Text
0.10.0
```

### Make sure you have done the following

- [X] I have updated to the latest version of the plugin.

**Comment by chrisgrieser** [comment]
Yeah, the plugin only removes the lines containing the marker emoji. Trying to detect anything more is not only quite convoluted, but also very error-prone (requiring special considerations for every single language, etc.)

The best approach for dealing with this is to add a `prettier-ignore` to the log statement, as described in the readme: https://github.com/chrisgrieser/nvim-chainsaw?tab=readme-ov-file#have-your-formatter-ignore-the-log-statements

**Comment by dlvhdr** [comment]
Oh nice, will it then remove the prettier comment as well?

**Comment by chrisgrieser** [comment]
yes, the `%s` at the end of the `/* prettier-ignore */ // %s` adds the emoji marker, ensuring that the line will also be removed by `removeLog`
