### ISSUE TITLE
[Bug]: require("chainsaw") returns "true" (boolean) instead of object

### ISSUE THREAD

**Issue by ishaan-kapoor** [chrisgrieser/nvim-chainsaw#17]
### Bug Description

I have this config
```lua
local function map(key, cmd, desc)
  key = "<leader>" .. key
  local opts = { noremap = true, silent = true, desc = desc }
  vim.api.nvim_set_keymap("n", key, cmd, opts)
end

function plugin.config()
  local chainsaw = require("chainsaw")
  map("lv", chainsaw.variableLog, "[L]og [V]ariable")
  map("lo", chainsaw.objectLog, "[L]og [O]bject")
  map("la", chainsaw.assertLog, "[L]og [A]ssert")
  map("lm", chainsaw.messageLog, "[L]og [M]essage")
  map("ls", chainsaw.stackTraceLog, "[L]og [S]tackTrace")
  map("lb", chainsaw.beepLog, "[L]og [B]eep")
  map("lt", chainsaw.timeLog, "[L]og [T]ime")
  map("ld", chainsaw.debugLog, "[L]og [D]ebug")
  map("lr", chainsaw.removeLogs, "[L]og [R]emove")
  chainsaw.setup({ marker = "Something unique" })
end
```
And I get the error `attempt to index local 'chainsaw' (a boolean value)`
Methods like `require("chainsaw").variableLog()` and `require("chainsaw").setup()` are used in the README.

### To Reproduce

I am using lazy.nvim plugin manager
`require("chainsaw").setup()`

### neovim version

```Text
NVIM v0.9.6-dev-0ef2718  
Released: 19th Jan, 2024
```

### Make sure you have done the following

- [X] I have updated to the latest version of the plugin.

**Comment by chrisgrieser** [comment]
> NVIM v0.9.6-dev-0ef2718 

from the readme:
> **Requirements**
> - nvim 0.10 or higher.

**Comment by ishaan-kapoor** [comment]
There was no such message when I require chainsaw.
Also, there is no error flagged in check-health.

Sorry, I didn't notice the minimum required version in the README.

**Comment by chrisgrieser** [comment]
> There was no such message when I require chainsaw.

It's a pretty simple `vim.notify`. If it did not occur for you, there is probably some issue with your config regarding the message systems. 

> Also, there is no error flagged in check-health.

I didn't add this plugin to the health check, since the warning message normally suffices.
